# Hypothesis not using matrix

In [2]:
import tensorflow as tf

In [3]:
#data
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [4]:
#placeholders for a tensor that will be always fed

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [6]:
hypothesis = w1 * x1 + w2*x2 + w3*x3 + b

In [7]:
#cost/loss function 정의
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

In [8]:
#Minimize! 
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [9]:
#graph를 session에 launch
sess = tf.Session()

In [10]:
#Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

In [11]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, 
                                              Y : y_data})

    if step % 10 == 0:
        print('Step: ', step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

Step:  0 Cost:  78622.9 
Prediction:
 [ -84.43641  -123.056015 -109.96021  -120.89328   -98.44864 ]
Step:  10 Cost:  85.16109 
Prediction:
 [163.43849 174.93837 183.62378 198.81606 128.85968]
Step:  20 Cost:  83.988205 
Prediction:
 [164.15308 175.86427 184.50125 199.7753  129.57953]
Step:  30 Cost:  83.53668 
Prediction:
 [164.11995 175.89133 184.49313 199.77017 129.61372]
Step:  40 Cost:  83.08732 
Prediction:
 [164.08461 175.91559 184.48235 199.7621  129.64575]
Step:  50 Cost:  82.64055 
Prediction:
 [164.0494  175.93977 184.47159 199.75407 129.6777 ]
Step:  60 Cost:  82.19633 
Prediction:
 [164.01427 175.96387 184.46085 199.74606 129.70955]
Step:  70 Cost:  81.75444 
Prediction:
 [163.97925 175.98792 184.45016 199.73808 129.74133]
Step:  80 Cost:  81.314896 
Prediction:
 [163.9443  176.01189 184.4395  199.73007 129.77301]
Step:  90 Cost:  80.87774 
Prediction:
 [163.90944 176.03578 184.42882 199.7221  129.80458]
Step:  100 Cost:  80.44314 
Prediction:
 [163.87471 176.05962 184.4182

Step:  910 Cost:  52.01319 
Prediction:
 [161.35178 177.79128 183.64778 199.1365  132.12576]
Step:  920 Cost:  51.73449 
Prediction:
 [161.32397 177.81033 183.63928 199.1301  132.151  ]
Step:  930 Cost:  51.45714 
Prediction:
 [161.29625 177.82938 183.63081 199.12372 132.1762 ]
Step:  940 Cost:  51.18136 
Prediction:
 [161.2686  177.84836 183.62239 199.11739 132.20132]
Step:  950 Cost:  50.906956 
Prediction:
 [161.24103 177.86731 183.61398 199.11105 132.2264 ]
Step:  960 Cost:  50.634056 
Prediction:
 [161.2135  177.88617 183.60556 199.10472 132.25137]
Step:  970 Cost:  50.362637 
Prediction:
 [161.18607 177.90501 183.5972  199.09842 132.27629]
Step:  980 Cost:  50.092754 
Prediction:
 [161.15874 177.9238  183.58884 199.09212 132.30115]
Step:  990 Cost:  49.82439 
Prediction:
 [161.13145 177.9425  183.58052 199.08585 132.32593]
Step:  1000 Cost:  49.557335 
Prediction:
 [161.10423 177.96118 183.57222 199.07959 132.35065]
Step:  1010 Cost:  49.29176 
Prediction:
 [161.07709 177.9798  1

Step:  1950 Cost:  29.783203 
Prediction:
 [158.82971 179.52281 182.87823 198.55437 134.4196 ]
Step:  1960 Cost:  29.624496 
Prediction:
 [158.80876 179.53719 182.87186 198.5495  134.43869]
Step:  1970 Cost:  29.466589 
Prediction:
 [158.78787 179.55156 182.8655  198.54468 134.45773]
Step:  1980 Cost:  29.309574 
Prediction:
 [158.76704 179.56587 182.85913 198.53984 134.47672]
Step:  1990 Cost:  29.153393 
Prediction:
 [158.74626 179.58014 182.8528  198.53502 134.49565]
Step:  2000 Cost:  28.99801 
Prediction:
 [158.72552 179.59438 182.84648 198.53018 134.51453]


# Hypothesis using Matrix

In [20]:
#data를 matrix로!
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.],
          [96., 98., 100.],[73., 66., 70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

In [21]:
#placeholder for a tensor
#None을 통해서 instance가 늘어나도 shape을 유지하도로 함. (numpy의 -1)
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [22]:
#hypothesis: XW + b
hypothesis = tf.matmul(X,W) + b

In [23]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [24]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [25]:
sess = tf.Session()

In [26]:
sess.run(tf.global_variables_initializer())

In [27]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis, train],
                                  feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print('step: ', step, ', cost: ', cost_val, 
             '\nPrediction: \n', hy_val)

step:  0 , cost:  4462.9717 
Prediction: 
 [[216.37251]
 [251.95378]
 [252.54146]
 [273.04044]
 [191.90729]]
step:  10 , cost:  13.936002 
Prediction: 
 [[157.35338]
 [181.04448]
 [182.65909]
 [196.94211]
 [137.82664]]
step:  20 , cost:  13.821642 
Prediction: 
 [[157.16043]
 [180.83977]
 [182.44322]
 [196.70882]
 [137.67578]]
step:  30 , cost:  13.748309 
Prediction: 
 [[157.1455 ]
 [180.84897]
 [182.43816]
 [196.70508]
 [137.68808]]
step:  40 , cost:  13.675425 
Prediction: 
 [[157.13115]
 [180.8588 ]
 [182.43373]
 [196.70204]
 [137.70082]]
step:  50 , cost:  13.602995 
Prediction: 
 [[157.11685]
 [180.86858]
 [182.42934]
 [196.69904]
 [137.71353]]
step:  60 , cost:  13.530882 
Prediction: 
 [[157.10258]
 [180.87834]
 [182.42493]
 [196.69601]
 [137.72621]]
step:  70 , cost:  13.459239 
Prediction: 
 [[157.08836]
 [180.88808]
 [182.42056]
 [196.69302]
 [137.73885]]
step:  80 , cost:  13.387904 
Prediction: 
 [[157.07416]
 [180.89778]
 [182.41618]
 [196.69002]
 [137.75145]]
step:  90 ,

step:  930 , cost:  8.542757 
Prediction: 
 [[155.99748]
 [181.6345 ]
 [182.08447]
 [196.46399]
 [138.70651]]
step:  940 , cost:  8.49802 
Prediction: 
 [[155.98624]
 [181.64218]
 [182.081  ]
 [196.46164]
 [138.71649]]
step:  950 , cost:  8.453477 
Prediction: 
 [[155.97499]
 [181.64986]
 [182.07753]
 [196.45929]
 [138.72643]]
step:  960 , cost:  8.409201 
Prediction: 
 [[155.9638 ]
 [181.65753]
 [182.0741 ]
 [196.45697]
 [138.73634]]
step:  970 , cost:  8.365177 
Prediction: 
 [[155.95265]
 [181.66516]
 [182.07065]
 [196.45462]
 [138.74623]]
step:  980 , cost:  8.321329 
Prediction: 
 [[155.9415 ]
 [181.67279]
 [182.06721]
 [196.4523 ]
 [138.75609]]
step:  990 , cost:  8.27778 
Prediction: 
 [[155.9304 ]
 [181.68037]
 [182.06378]
 [196.45   ]
 [138.76593]]
step:  1000 , cost:  8.234436 
Prediction: 
 [[155.91933]
 [181.68796]
 [182.06038]
 [196.4477 ]
 [138.77574]]
step:  1010 , cost:  8.19132 
Prediction: 
 [[155.90828]
 [181.69553]
 [182.05696]
 [196.44537]
 [138.7855 ]]
step:  1020

step:  1810 , cost:  5.400279 
Prediction: 
 [[155.11435]
 [182.2385 ]
 [181.81201]
 [196.28104]
 [139.48724]]
step:  1820 , cost:  5.3724775 
Prediction: 
 [[155.10547]
 [182.24457]
 [181.80928]
 [196.2792 ]
 [139.49509]]
step:  1830 , cost:  5.344825 
Prediction: 
 [[155.0966 ]
 [182.25061]
 [181.80653]
 [196.2774 ]
 [139.5029 ]]
step:  1840 , cost:  5.3173094 
Prediction: 
 [[155.08777]
 [182.25667]
 [181.8038 ]
 [196.27559]
 [139.51068]]
step:  1850 , cost:  5.289975 
Prediction: 
 [[155.07895]
 [182.26266]
 [181.8011 ]
 [196.27377]
 [139.51846]]
step:  1860 , cost:  5.262771 
Prediction: 
 [[155.07018]
 [182.26869]
 [181.7984 ]
 [196.27199]
 [139.52621]]
step:  1870 , cost:  5.2356844 
Prediction: 
 [[155.06142]
 [182.27469]
 [181.79567]
 [196.27019]
 [139.53395]]
step:  1880 , cost:  5.2087855 
Prediction: 
 [[155.05267]
 [182.28065]
 [181.79298]
 [196.26839]
 [139.54166]]
step:  1890 , cost:  5.182002 
Prediction: 
 [[155.04396]
 [182.28662]
 [181.79028]
 [196.2666 ]
 [139.54935