In [1]:
import numpy as np

1D Array

In [4]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])

print(t.ndim) #rank
print(t.shape) #shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


2D Array

In [5]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])

print(t.ndim) #rank
print(t.shape) #shape

2
(4, 3)


## Shape, Rank, Axis

In [6]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [10]:
sess = tf.Session()

t = tf.constant([1,2,3,4])
tf.shape(t).eval(session = sess)

array([4])

In [11]:
t = tf.constant([[1,2],[3,4]])

tf.shape(t).eval(session = sess)

array([2, 2])

In [14]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                 [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])

tf.shape(t).eval(session = sess)

array([1, 2, 3, 4])

axis: 제일 안 쪽이 가장 큰 값, 제일 바깥이 가장 작은 값

### Matmul VS multiply

In [15]:
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[1.],[2.]])
print('Metrix 1 shape', matrix1.shape)
print('Metrix 2 shape', matrix2.shape)
tf.matmul(matrix1, matrix2).eval(session = sess)  #matrix 곱

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [17]:
(matrix1*matrix2).eval(session = sess)  #element끼리의 곱

array([[1., 2.],
       [6., 8.]], dtype=float32)

## Broadcasting
-matrix끼리 shape이 다르더라도 연산이 가능하게 한다.

In [18]:
#1
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval(session = sess)

array([[4., 5.]], dtype=float32)

In [19]:
#2
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([3.,4.])
(matrix1 + matrix2).eval(session = sess)

array([[4., 6.]], dtype=float32)

In [20]:
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([[3.],[4.]])
(matrix1 + matrix2).eval(session=sess)

array([[4., 5.],
       [5., 6.]], dtype=float32)

## Reduce_mean
행렬의 값이 여러 개 있는데 하나로 줄여준다

In [22]:
#1
tf.reduce_mean([1,2], axis = 0).eval(session = sess)  #int가 input이면 output도 int

1

In [23]:
#2 
x = [[1.,2.],
     [3.,4.]]

tf.reduce_mean(x).eval(session = sess)

2.5

In [24]:
print('tf.reduce_mean(x, axis = 0):', tf.reduce_mean(x, axis = 0).eval(session = sess))
print('tf.reduce_mean(x, axis = 1): ', tf.reduce_mean(x, axis = 1).eval(session = sess))
print('tf.reduce_mean(x, axis = -1): ', tf.reduce_mean(x, axis = -1).eval(session = sess))

tf.reduce_mean(x, axis = 0): [2. 3.]
tf.reduce_mean(x, axis = 1):  [1.5 3.5]
tf.reduce_mean(x, axis = -1):  [1.5 3.5]


## Reduce_sum

In [25]:
x = [[1.,2.],
     [3.,4.]]

In [26]:
tf.reduce_sum(x).eval(session = sess)

10.0

In [27]:
tf.reduce_sum(x, axis = 0).eval(session = sess)

array([4., 6.], dtype=float32)

In [28]:
tf.reduce_sum(x, axis = 1).eval(session = sess)

array([3., 7.], dtype=float32)

In [30]:
#보통 가장 안쪽의 축으로 합을 구한 후 평균을 낸다 
tf.reduce_mean(tf.reduce_sum(x, axis =-1)).eval(session = sess)

5.0

## Argmax
- 가장 큰 값의 위치

In [31]:
x = [[0,1,2],
    [2,1,0]]

In [32]:
tf.argmax(x, axis = 0).eval(session = sess) 

array([1, 0, 0], dtype=int64)

In [33]:
tf.argmax(x, axis = 1).eval(session = sess)

array([2, 0], dtype=int64)

In [34]:
tf.argmax(x, axis = -1).eval(session = sess)

array([2, 0], dtype=int64)

## Reshape

In [35]:
t = np.array([[[0,1,2],
              [3,4,5]],
             [[6,7,8],
             [9,10,11]]])

t.shape

(2, 2, 3)

In [37]:
tf.reshape(t, shape = [-1,3]).eval(session = sess) #보통 가장 안쪽의 shape은 그대로 둔다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
tf.reshape(t, shape = [-1,1,3]).eval(session = sess)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

## Reshape (squeeze, expand)

In [39]:
tf.squeeze([[0],[1],[2]]).eval(session = sess) #concatenate

array([0, 1, 2])

In [40]:
tf.expand_dims([0,1,2],1).eval(session = sess)  #[3] => [3,1]

array([[0],
       [1],
       [2]])

## One hot

In [44]:
tf.one_hot([[0],[1],[2],[0]], depth = 3).eval(session = sess) #자동 expand_dims

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [45]:
t = tf.one_hot([[0],[1],[2],[0]], depth = 3).eval(session = sess) #자동 expand_dims
tf.reshape(t, shape = [-1, 3]).eval(session = sess)  #원하는 shape으로 바꾸기

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## Casting

In [47]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session = sess)  #int로 바꾸기

array([1, 2, 3, 4])

In [48]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval(session = sess)

array([1, 0, 1, 0])

## Stack

In [49]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x,y,z]).eval(session = sess)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
tf.stack([x,y,z], axis = 1).eval(session = sess)

array([[1, 2, 3],
       [4, 5, 6]])

## Ones and Zeros like
- 똑같은 모양의 1로 / 0으로 채워진 matrix 만들기

In [51]:
x = [[0,1,2],
    [2,1,0]]

In [52]:
tf.ones_like(x).eval(session = sess)

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
tf.zeros_like(x).eval(session = sess)

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

In [54]:
for x , y in zip([1,2,3],[4,5,6]):
    print(x, y)

1 4
2 5
3 6


In [55]:
for x, y, z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
