## Linear Regression _ tensorflow

In [93]:
import tensorflow as tf

In [94]:
x_train = [1,2,3]
y_train = [1,2,3]

#tf.Variable: tensorflow가 학습하는 과정에서 스스로 변경하는 값
#그 값의 shape을 결정해줘야 하는데 보통 random한 값을 주는 것
#[1]은 rank가 1인 shape을 정의하는 것
W = tf.Variable(tf.random_normal([1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#가설 정의
hypothesis = x_train * W + b

In [95]:
#cost 정의
#tf.reduce_mean: 특정 차원을 제거하고 평균을 구한다!
cost = tf.reduce_mean(tf.square(hypothesis - y_train)) 

In [96]:
#Gradient Descent를 0.01 learning rate로 실행하는 optimizer 만들기
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)  #optimizer를 통해 cost 최소화

In [97]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [98]:
for step in range(2001):
    sess.run(train)
    if step %20 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

0 9.881123 [-1.0463816] [1.4301822]
20 0.58134955 [0.06837] [1.8110436]
40 0.45189527 [0.20914163] [1.7685964]
60 0.40972862 [0.25554422] [1.6895416]
80 0.37211594 [0.29141024] [1.6105263]
100 0.33796158 [0.32479507] [1.5348744]
120 0.30694214 [0.3565351] [1.4627445]
140 0.27876973 [0.38677636] [1.3940011]
160 0.2531832 [0.41559574] [1.3284882]
180 0.22994506 [0.4430606] [1.2660542]
200 0.20883976 [0.46923468] [1.2065543]
220 0.18967168 [0.49417865] [1.1498508]
240 0.17226285 [0.51795036] [1.0958122]
260 0.15645182 [0.5406049] [1.044313]
280 0.14209212 [0.5621947] [0.9952342]
300 0.12905033 [0.58277] [0.94846183]
320 0.11720557 [0.60237825] [0.9038876]
340 0.10644797 [0.62106514] [0.86140823]
360 0.09667777 [0.63887364] [0.8209251]
380 0.08780428 [0.6558452] [0.78234464]
400 0.07974521 [0.6720193] [0.7455772]
420 0.072425894 [0.6874332] [0.71053773]
440 0.06577832 [0.70212275] [0.6771452]
460 0.059740946 [0.7161219] [0.64532185]
480 0.05425768 [0.7294631] [0.6149941]
500 0.04927766 [0.

placeholder를 사용해서 LR해보기!

In [99]:
X = tf.placeholder(tf.float32, shape = [None])  #여기서 shape: 1차원 array, 안의 갯수는 자유
Y = tf.placeholder(tf.float32, shape = [None])

In [100]:
hypothesis = X*W + b
cost = tf.reduce_mean(tf.square(hypothesis - Y)) 

In [102]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

In [103]:
for step in range(2001):
    cost_val, W_val, b_val,_= sess.run([cost, W, b, train],
                                        feed_dict = {X:[1,2,3,4,5],Y:[2.1,3.1,4.1,5.1,6.1]})
    if step %20 == 0:
        print(step, cost_val, W_val, b_val)

0 1.2100917 [0.999943] [0.00012929]
20 0.16588227 [1.2631276] [0.1450575]
40 0.14484802 [1.2470838] [0.20792668]
60 0.12649687 [1.2309074] [0.26635072]
80 0.11047063 [1.215785] [0.32094714]
100 0.09647478 [1.2016531] [0.37196794]
120 0.084252246 [1.1884468] [0.41964728]
140 0.07357808 [1.1761053] [0.46420404]
160 0.06425623 [1.164572] [0.50584286]
180 0.05611552 [1.153794] [0.5447546]
200 0.04900607 [1.1437218] [0.5811181]
220 0.042797368 [1.1343095] [0.61510015]
240 0.03737528 [1.1255134] [0.64685655]
260 0.03264005 [1.1172935] [0.67653346]
280 0.028504808 [1.1096117] [0.7042666]
300 0.024893478 [1.1024332] [0.7301833]
320 0.02173968 [1.0957248] [0.754403]
340 0.018985402 [1.0894557] [0.77703637]
360 0.016580116 [1.0835972] [0.79818755]
380 0.0144795105 [1.0781224] [0.8179535]
400 0.012645071 [1.073006] [0.83642495]
420 0.011043052 [1.0682248] [0.8536867]
440 0.009643963 [1.0637567] [0.8698179]
460 0.008422159 [1.0595813] [0.88489276]
480 0.0073551326 [1.0556792] [0.8989802]
500 0.006

In [76]:
print(sess.run(hypothesis, feed_dict = {X:[5]}))

[6.1000085]


In [77]:
print(sess.run(hypothesis, feed_dict = {X:[2.5]}))

[3.5999942]


In [78]:
print(sess.run(hypothesis, feed_dict = {X:[1.5, 3,5]}))

[2.5999885 4.099997  6.1000085]


## Linear Regression _ pytorch

In [133]:
import torch
from torch.autograd import Variable
from torch.nn import Linear, Module, MSELoss
from torch.optim import SGD
import numpy as np

In [131]:
x_train = torch.tensor([1,2,3])
y_train = torch.tensor([1,2,3])

In [134]:
W = torch.randn(1)

In [130]:
hypothesis = W*x_train + b

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
loss = (hypothesis - y_train).pow(2).mean()

In [142]:
class LinearRegressionModel(Module):
    def __init__(self, input_dim, output_dim):
        
        super(LinearRegressionModel, self).__init__()
        self.linear = Linear(input_dim, output_dim)
        
    def forward(self,x):
        out = self.linear
        return out
    

In [143]:
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

criterion = MSELoss()
l_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = l_rate)

epochs = 2000

In [144]:
for epoch in range(epochs):
    
    epoch += 1
    
    inputs = Variable(torch(x_train))
    labels = Variable(torch.from_numpy(y_train))
    
    optimizer.zero_grad()
    
    ouptuts = model.forward(inputs)
    loss = criterion(output, labels)
    loss.backward()
    optimizer.step()
    print('epoch {}, loss {}'.format(epoch, loss.data[0]))

TypeError: expected np.ndarray (got Tensor)

In [ ]:
predicted = model.forward(Variable(torch.from_numpy(x_train))).data.numpy()

plt.plot(x_train, y_train, 'go',labe = 'from data', alpha = .5)
