In [33]:
import torch
from torch import nn, optim
from torch.autograd import Variable
import numpy as np

In [34]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

input_dim = len(x_data[0])
output_dim = len(y_data[0])

X = Variable(torch.tensor(x_data)).float()
Y = Variable(torch.tensor(y_data)).float()

In [77]:
linear = nn.Linear(input_dim, output_dim, bias = True)
softmax = nn.Softmax(dim = 1)
model = nn.Sequential(linear, softmax)

lr = 0.1
optimiser = optim.SGD(model.parameters(), lr = lr)

In [83]:
for step in range(2001):
    optimiser.zero_grad()
    
    outputs = model(X)
    cost = -(Y*torch.log(outputs)).sum(1).mean()
    cost.backward()
    optimiser.step()
    
    if step % 20 == 0:
        print('parameters: ', end = '')
        for i in model.parameters():
            print(i.data.numpy())
        print('step {}, loss {}, \nPrediction:{}'.format(step, cost.item(), outputs.data.numpy()))
        print( )

predicted = model(X).argmax(1)
accuracy = (predicted == Y.argmax(1)).float().mean()

print('Prediction: ', predicted, '\n Accuracy: ', accuracy.data)
            

parameters: [[-4.2171803  -0.9488162   3.9748914  -1.1412985 ]
 [ 0.5684626  -0.55055445 -0.5517076   1.6625707 ]
 [ 3.44968     0.49655026 -2.747666   -0.16821793]]
[-3.190884  -1.1220738  4.7156315]
step 0, loss 0.15938349068164825, 
Prediction:[[3.0121532e-06 1.1293793e-03 9.9886763e-01]
 [1.4275475e-03 8.3253205e-02 9.1531926e-01]
 [8.7251337e-08 1.6561708e-01 8.3438283e-01]
 [1.9303877e-06 8.4859478e-01 1.5140329e-01]
 [2.6020524e-01 7.2754985e-01 1.2244926e-02]
 [1.3694964e-01 8.6303794e-01 1.2409393e-05]
 [7.4875075e-01 2.5122273e-01 2.6484913e-05]
 [9.1805536e-01 8.1944130e-02 4.3918359e-07]]

parameters: [[-4.233823   -0.95271957  3.9975748  -1.152389  ]
 [ 0.5727922  -0.5504517  -0.5578409   1.6700485 ]
 [ 3.4619944   0.5003507  -2.7642164  -0.1646055 ]]
[-3.2071707 -1.1276371  4.7374816]
step 20, loss 0.15824860334396362, 
Prediction:[[2.8425316e-06 1.0976577e-03 9.9889946e-01]
 [1.4066136e-03 8.2638800e-02 9.1595459e-01]
 [8.1152088e-08 1.6446574e-01 8.3553421e-01]
 [1.8433

parameters: [[-4.7230887  -1.068843    4.6756973  -1.4878154 ]
 [ 0.70068794 -0.5469214  -0.74472415  1.8948724 ]
 [ 3.8233652   0.61294454 -3.2554522  -0.05400101]]
[-3.6870272 -1.2901634  5.3798656]
step 680, loss 0.12792763113975525, 
Prediction:[[5.1570083e-07 4.7501113e-04 9.9952447e-01]
 [9.2591788e-04 6.6237018e-02 9.3283707e-01]
 [9.5165467e-09 1.3355134e-01 8.6644870e-01]
 [4.7828831e-07 8.7836820e-01 1.2163128e-01]
 [2.1459186e-01 7.7574831e-01 9.6598277e-03]
 [1.1322445e-01 8.8677078e-01 4.7692401e-06]
 [7.8141612e-01 2.1857405e-01 9.8776709e-06]
 [9.4210780e-01 5.7892069e-02 9.6560541e-08]]

parameters: [[-4.7363453  -1.0720276   4.6943665  -1.497146  ]
 [ 0.704162   -0.54681396 -0.74995196  1.9010944 ]
 [ 3.8331475   0.61602193 -3.2688932  -0.05089244]]
[-3.7000535 -1.2945534  5.3972816]
step 700, loss 0.12718366086483002, 
Prediction:[[4.9235001e-07 4.6433895e-04 9.9953520e-01]
 [9.1588718e-04 6.5835111e-02 9.3324906e-01]
 [8.9768495e-09 1.3278836e-01 8.6721158e-01]
 [4.6

parameters: [[-5.1337714  -1.168476    5.260989   -1.7824371 ]
 [ 0.8083047  -0.5433591  -0.9103102   2.090685  ]
 [ 4.1264324   0.70901746 -3.6751573   0.04480898]]
[-4.091036  -1.4261997  5.9199104]
step 1360, loss 0.10660357028245926, 
Prediction:[[1.2245236e-07 2.3461691e-04 9.9976522e-01]
 [6.6783786e-04 5.4739073e-02 9.4459307e-01]
 [1.5493087e-09 1.1159498e-01 8.8840503e-01]
 [1.5610888e-07 8.9865237e-01 1.0134750e-01]
 [1.8222418e-01 8.0981618e-01 7.9596117e-03]
 [9.6290350e-02 9.0370750e-01 2.1920303e-06]
 [8.0708981e-01 1.9290581e-01 4.4150802e-06]
 [9.5706087e-01 4.2939167e-02 2.8004415e-08]]

parameters: [[-5.1447425  -1.1711651   5.276816   -1.7904607 ]
 [ 0.81117773 -0.54325753 -0.9148325   2.0960002 ]
 [ 4.13453     0.71160495 -3.6864622   0.04751717]]
[-4.10184   -1.4298375  5.934353 ]
step 1380, loss 0.10608067363500595, 
Prediction:[[1.17830673e-07 2.30227510e-04 9.99769628e-01]
 [6.62233972e-04 5.44579253e-02 9.44879830e-01]
 [1.47572332e-09 1.11054525e-01 8.88945520

parameters: [[-5.45958    -1.2489403   5.735073   -2.0239358 ]
 [ 0.8935414  -0.54020774 -1.0466567   2.250323  ]
 [ 4.3670053   0.7863303  -4.012904    0.12666829]]
[-4.4121246 -1.534381   6.3491855]
step 2000, loss 0.0920306146144867, 
Prediction:[[3.9006476e-08 1.3375208e-04 9.9986625e-01]
 [5.2334153e-04 4.6918284e-02 9.5255834e-01]
 [3.6389441e-10 9.6485458e-02 9.0351450e-01]
 [6.4809100e-08 9.1256106e-01 8.7438837e-02]
 [1.5942028e-01 8.3376217e-01 6.8175243e-03]
 [8.4321849e-02 9.1567695e-01 1.1797171e-06]
 [8.2654810e-01 1.7344947e-01 2.3192940e-06]
 [9.6642852e-01 3.3571463e-02 1.0420164e-08]]

Prediction:  tensor([2, 2, 2, 1, 1, 1, 0, 0]) 
 Accuracy:  tensor(1.)


In [92]:
# Testing
print('--------------')
a = model(Variable(torch.Tensor([[1, 11, 7, 9]])))
print(a.data.numpy(), a.argmax(1))

print('--------------')
b = model(Variable(torch.Tensor([[1, 3, 4, 3]])))
print(b.data.numpy(), b.argmax(1))

print('--------------')
c = model(Variable(torch.Tensor([[1, 1, 0, 1]])))
print(c.data.numpy(), c.argmax(1))

print('--------------')
all = model(Variable(torch.Tensor([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])))
print(all.data.numpy(), all.argmax(1))

--------------
[[3.2768023e-04 9.9967146e-01 8.9360418e-07]] tensor([1])
--------------
[[0.94752324 0.04973813 0.00273864]] tensor([0])
--------------
[[1.7413151e-11 2.5934416e-05 9.9997401e-01]] tensor([2])
--------------
[[3.2768023e-04 9.9967146e-01 8.9360333e-07]
 [9.4752324e-01 4.9738083e-02 2.7386395e-03]
 [1.7413151e-11 2.5934416e-05 9.9997401e-01]] tensor([1, 0, 2])


## Zoo Classifier

In [188]:
xy = np.loadtxt('data-04-zoo.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:,:-1]
y_data = xy[:,[-1]]

input_dim = len(x_data[0])
output_dim = len(y_data[0])
nb_classes = int(y_data.max() + 1)

X = Variable(torch.tensor(x_data)).float()
Y = Variable(torch.tensor(y_data)).float()

#Y: one_hot_encoding
Y_one_hot = torch.zeros([len(y_data), nb_classes])
Y_one_hot = Y_one_hot.scatter_(1, Y.long(), 1)
Y_one_hot = Variable(Y_one_hot)

input_dim = len(x_data[0])
nb_classes = len(Y_one_hot[0])

In [202]:
linear = nn.Linear(input_dim, nb_classes, bias = True)
softmax = nn.Softmax(dim = 1)
model = nn.Sequential(linear, softmax)

lr = 0.1
optimiser = optim.SGD(model.parameters(), lr = lr)

In [203]:
for step in range(2001):
    optimiser.zero_grad()
    
    outputs = model(X)
    cost = -(Y_one_hot*torch.log(outputs)).sum(1).mean()
    cost.backward(retain_graph = True)
    optimiser.step()
    
    if step % 20 == 0:
        predicted = outputs.argmax(1)
        accuracy = (predicted == Y.long().squeeze()).float().mean()
        print('step {}, cost {}, \n Accuracy: {}'.format(step, cost.item(), accuracy.data))
        print( )


step 0, cost 1.953212022781372, 
 Accuracy: 0.19801980257034302

step 20, cost 1.0272934436798096, 
 Accuracy: 0.7722772359848022

step 40, cost 0.759106457233429, 
 Accuracy: 0.8217821717262268

step 60, cost 0.6213203072547913, 
 Accuracy: 0.8712871074676514

step 80, cost 0.5363105535507202, 
 Accuracy: 0.8712871074676514

step 100, cost 0.4770602583885193, 
 Accuracy: 0.8712871074676514

step 120, cost 0.43241992592811584, 
 Accuracy: 0.9009901285171509

step 140, cost 0.3970254063606262, 
 Accuracy: 0.9207921028137207

step 160, cost 0.3679611384868622, 
 Accuracy: 0.9306930899620056

step 180, cost 0.34348636865615845, 
 Accuracy: 0.9306930899620056

step 200, cost 0.32248446345329285, 
 Accuracy: 0.9504950642585754

step 220, cost 0.30419740080833435, 
 Accuracy: 0.9504950642585754

step 240, cost 0.2880869209766388, 
 Accuracy: 0.9504950642585754

step 260, cost 0.2737570106983185, 
 Accuracy: 0.9504950642585754

step 280, cost 0.2609076499938965, 
 Accuracy: 0.9603960514068604

In [200]:
for p, y in zip(predicted, Y.long().squeeze()):
    print("[{}] Prediction: {} True Y: {}".format(bool(p.item() == y.item()), p.item(), y.item()))

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 5 True Y: 5
[True] Prediction: 0 True Y: 0
[True] P