In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np

In [2]:
x_train = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.],[96., 98., 100.],[73.,66.,70.]]
y_train = [[152.],[185.],[180.],[196.],[142.]]

trainX = Variable(torch.tensor(x_train))
trainY = Variable(torch.tensor(y_train))

In [3]:
class MultiVariableLinearRegression(nn.Module):
    
    def __init__(self, input_dim, output_dim, bias = True):
        super(MultiVariableLinearRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim, bias)
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [4]:
#hypothesis 
model = MultiVariableLinearRegression(3, 1, bias = True)

#cost: MSE
criterion = nn.MSELoss()

learning_rate = 1e-5
#minimize
optimiser = torch.optim.SGD(model.parameters(), lr = learning_rate)

### Traing the Model

In [5]:
epochs = 2000

for epoch in range(1, epochs + 1):
    
    #Clears the gradients of all optimized  tensors (set gradients as 0)
    optimiser.zero_grad()
    
    #forward to get predicted value
    outputs = model.forward(trainX)
    loss = criterion(outputs, trainY)
    loss.backward() #apply backpropagation
    optimiser.step()  #update the parameters
    if epoch % 20 == 0:
        print('parameters: ', end = '')
        for i in model.parameters():
            print(i.data.numpy())
        print('epoch {}, loss {}, \nPrediction:{}'.format(epoch, loss.item(), outputs.data.numpy()))
        print( )

parameters: [[0.53848577 0.5674875  0.90852374]]
[-0.560057]
epoch 20, loss 1.837317943572998, 
Prediction:[[152.2869 ]
 [183.94904]
 [180.77237]
 [197.5993 ]
 [139.79877]]

parameters: [[0.5396032 0.5664179 0.9084945]]
[-0.5600105]
epoch 40, loss 1.8253246545791626, 
Prediction:[[152.28192]
 [183.95757]
 [180.7733 ]
 [197.6004 ]
 [139.80884]]

parameters: [[0.54070896 0.56534797 0.90845746]]
[-0.559964]
epoch 60, loss 1.8134756088256836, 
Prediction:[[152.2743 ]
 [183.96286]
 [180.77107]
 [197.59805]
 [139.81639]]

parameters: [[0.54180974 0.5642842  0.90841925]]
[-0.5599175]
epoch 80, loss 1.8017463684082031, 
Prediction:[[152.26674]
 [183.96812]
 [180.76886]
 [197.59572]
 [139.82391]]

parameters: [[0.54290545 0.5632267  0.9083799 ]]
[-0.559871]
epoch 100, loss 1.7901216745376587, 
Prediction:[[152.25922]
 [183.97336]
 [180.76665]
 [197.59338]
 [139.8314 ]]

parameters: [[0.5439961  0.56217533 0.9083395 ]]
[-0.5598245]
epoch 120, loss 1.7786198854446411, 
Prediction:[[152.25175]
 [1

parameters: [[0.59092635 0.51834214 0.90521014]]
[-0.5576722]
epoch 1080, loss 1.345117211341858, 
Prediction:[[151.93835]
 [184.19693]
 [180.67291]
 [197.4899 ]
 [140.15494]]

parameters: [[0.5918006  0.51755506 0.90512264]]
[-0.5576281]
epoch 1100, loss 1.3381208181381226, 
Prediction:[[151.9327 ]
 [184.20088]
 [180.67125]
 [197.48798]
 [140.16075]]

parameters: [[0.59267116 0.5167726  0.90503436]]
[-0.557584]
epoch 1120, loss 1.3312387466430664, 
Prediction:[[151.92706]
 [184.20482]
 [180.66963]
 [197.48608]
 [140.1665 ]]

parameters: [[0.59353787 0.51599497 0.904945  ]]
[-0.5575399]
epoch 1140, loss 1.3243999481201172, 
Prediction:[[151.92146]
 [184.20872]
 [180.66801]
 [197.48419]
 [140.17226]]

parameters: [[0.5944006  0.51522195 0.90485495]]
[-0.5574958]
epoch 1160, loss 1.317628026008606, 
Prediction:[[151.91591]
 [184.21262]
 [180.66638]
 [197.4823 ]
 [140.17796]]

parameters: [[0.5952597 0.5144535 0.9047642]]
[-0.55745167]
epoch 1180, loss 1.3109441995620728, 
Prediction:[[15

## Loading Data from file

In [55]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)

In [56]:
x = xy[:,:-1]
y = xy[:,[-1]]  #마지막 값만!

In [57]:
train_X = Variable(torch.tensor(x, dtype = torch.float32))
train_Y = Variable(torch.tensor(y, dtype = torch.float32))

In [28]:
model = MultiVariableLinearRegression(len(x[0]), len(y[0]), bias = True)

criterion = nn.MSELoss()
lr = 1e-5
optimiser = optim.SGD(model.parameters(), lr = lr)


In [29]:
epochs = 2000

for epoch in range(1, epochs):
    
    optimiser.zero_grad()
    
    outputs = model.forward(train_X)
    loss = criterion(outputs, train_Y)
    loss.backward()
    optimiser.step()
    
    if epoch % 200 == 0:
        for i in model.parameters():
            print(i.data.numpy())
        print('epoch  {},  loss {},  \nPrediction: {}'.format(epoch, loss, outputs.data.numpy()))
        
print('\nreal Y: \n', y)

[[0.8702218  0.19285089 0.9524513 ]]
[0.3876486]
epoch  200,  loss 11.330975532531738,  
Prediction: [[150.77513]
 [186.86774]
 [181.10735]
 [198.07329]
 [143.31445]
 [107.76605]
 [148.04204]
 [109.23361]
 [177.05357]
 [166.45116]
 [143.46135]
 [144.32034]
 [186.31218]
 [154.09238]
 [149.67207]
 [189.91776]
 [147.49614]
 [176.80905]
 [176.62006]
 [157.60999]
 [174.05112]
 [175.80908]
 [165.22935]
 [150.15477]
 [192.3474 ]]
[[0.84528947 0.21149862 0.95846236]]
[0.3873923]
epoch  400,  loss 10.82789134979248,  
Prediction: [[150.89749]
 [186.74878]
 [181.12605]
 [198.10812]
 [143.14563]
 [107.63275]
 [148.16428]
 [109.46652]
 [176.89833]
 [166.31549]
 [143.48491]
 [144.23172]
 [186.31177]
 [154.0531 ]
 [149.75671]
 [189.83548]
 [147.35849]
 [177.02664]
 [176.65833]
 [157.67566]
 [174.15114]
 [175.72871]
 [165.34311]
 [150.23422]
 [192.25891]]
[[0.8215612  0.22904603 0.96437854]]
[0.38713208]
epoch  600,  loss 10.374593734741211,  
Prediction: [[151.01262 ]
 [186.63612 ]
 [181.14325 ]
 [1

In [31]:
print("Your score will be ", model(Variable(torch.Tensor([[100, 70, 101]]))).data.numpy())
print("Other scores will be ", model(Variable(torch.Tensor([[60, 70, 110], [90, 100, 80]]))).data.numpy())

Your score will be  [[182.73093]]
Other scores will be  [[176.84613]
 [178.33786]]


## Batch

In [37]:
import torch.utils.data as data_utils

In [62]:
#Dataloader를 통해 mini batch로 나눠주기
traindata = data_utils.TensorDataset(train_X, train_Y)

#DataLoader: Combines a dataset and a sampler, and provides single- or multi-process iterators over the dataset.
batch_size = 10
train = data_utils.DataLoader(dataset = traindata, batch_size = batch_size, shuffle = True)
batch_num = len(traindata) / batch_size

In [59]:
trainX

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])

In [65]:
for epoch in range(1, epochs):
    for step, (x_data, label) in enumerate(train):
        b_x, b_y = Variable(x_data), Variable(label).type(torch.float32)   # batch x, batch y
        
        optimiser.zero_grad()
    
        outputs = model.forward(train_X)
        loss = criterion(outputs, train_Y)
        loss.backward()
        optimiser.step()
    
    if epoch % 200 == 0:
        for i in model.parameters():
            print(i.data.numpy())
        print('epoch  {},  loss {},  \nPrediction: {}'.format(epoch, loss, outputs.data.numpy()))
        
print('\nreal Y: \n', y)

[[0.36858734 0.6654382  0.98430103]]
[-0.12289222]
epoch  200,  loss 6.947421550750732,  
Prediction: [[153.84161 ]
 [184.25427 ]
 [181.82333 ]
 [198.90454 ]
 [139.60397 ]
 [104.15895 ]
 [150.34323 ]
 [113.523315]
 [173.10092 ]
 [162.19467 ]
 [143.74428 ]
 [141.76999 ]
 [186.94376 ]
 [154.08453 ]
 [151.0307  ]
 [187.87262 ]
 [145.46725 ]
 [181.16211 ]
 [178.183   ]
 [159.64948 ]
 [175.91605 ]
 [173.74434 ]
 [167.52388 ]
 [153.00648 ]
 [190.65584 ]]
[[0.36858734 0.6654382  0.98430103]]
[-0.12289222]
epoch  400,  loss 6.947421550750732,  
Prediction: [[153.84161 ]
 [184.25427 ]
 [181.82333 ]
 [198.90454 ]
 [139.60397 ]
 [104.15895 ]
 [150.34323 ]
 [113.523315]
 [173.10092 ]
 [162.19467 ]
 [143.74428 ]
 [141.76999 ]
 [186.94376 ]
 [154.08453 ]
 [151.0307  ]
 [187.87262 ]
 [145.46725 ]
 [181.16211 ]
 [178.183   ]
 [159.64948 ]
 [175.91605 ]
 [173.74434 ]
 [167.52388 ]
 [153.00648 ]
 [190.65584 ]]
[[0.36858734 0.6654382  0.98430103]]
[-0.12289222]
epoch  600,  loss 6.947421550750732,  
Pred