# Hypothesis not using matrix

In [28]:
import tensorflow as tf

In [29]:
#data
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [30]:
#placeholders for a tensor that will be always fed

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [31]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [32]:
hypothesis = w1 * x1 + w2*x2 + w3*x3 + b

In [33]:
#cost/loss function 정의
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

In [34]:
#Minimize! 
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [35]:
#graph를 session에 launch
sess = tf.Session()

In [36]:
#Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

In [37]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, 
                                              Y : y_data})

    if step % 10 == 0:
        print('Step: ', step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

Step:  0 Cost:  66570.02 
Prediction:
 [ -79.33792  -88.97003  -90.94183 -101.47381  -63.84744]
Step:  10 Cost:  6.2758675 
Prediction:
 [148.90161 185.3419  179.35014 192.86703 145.38004]
Step:  20 Cost:  5.6423826 
Prediction:
 [149.60004 186.16643 180.17027 193.75981 146.00551]
Step:  30 Cost:  5.61835 
Prediction:
 [149.61    186.16348 180.1751  193.76471 145.99985]
Step:  40 Cost:  5.594461 
Prediction:
 [149.61783 186.15808 180.17743 193.76692 145.99228]
Step:  50 Cost:  5.57069 
Prediction:
 [149.62563 186.15263 180.17975 193.76913 145.98474]
Step:  60 Cost:  5.5470457 
Prediction:
 [149.63345 186.14725 180.1821  193.77133 145.97723]
Step:  70 Cost:  5.523537 
Prediction:
 [149.64124 186.14188 180.18442 193.77353 145.96974]
Step:  80 Cost:  5.5001593 
Prediction:
 [149.64897 186.13654 180.18672 193.77571 145.96225]
Step:  90 Cost:  5.4768686 
Prediction:
 [149.6567  186.13116 180.18903 193.7779  145.95477]
Step:  100 Cost:  5.453738 
Prediction:
 [149.6644  186.12582 180.19131 1

Step:  960 Cost:  3.8583565 
Prediction:
 [150.25291 185.71793 180.36594 193.9505  145.37486]
Step:  970 Cost:  3.843741 
Prediction:
 [150.25894 185.71375 180.3677  193.95232 145.36894]
Step:  980 Cost:  3.8291557 
Prediction:
 [150.26497 185.70955 180.3695  193.95412 145.363  ]
Step:  990 Cost:  3.814706 
Prediction:
 [150.27097 185.70537 180.37126 193.95587 145.3571 ]
Step:  1000 Cost:  3.8002975 
Prediction:
 [150.277   185.70122 180.37305 193.95769 145.35124]
Step:  1010 Cost:  3.785942 
Prediction:
 [150.28297 185.69708 180.3748  193.95947 145.34535]
Step:  1020 Cost:  3.7716815 
Prediction:
 [150.28893 185.69293 180.37656 193.96126 145.3395 ]
Step:  1030 Cost:  3.7574997 
Prediction:
 [150.29486 185.68881 180.37833 193.96304 145.33365]
Step:  1040 Cost:  3.7434144 
Prediction:
 [150.30081 185.68471 180.3801  193.9648  145.32784]
Step:  1050 Cost:  3.7293758 
Prediction:
 [150.3067  185.68059 180.38182 193.96655 145.322  ]
Step:  1060 Cost:  3.7154365 
Prediction:
 [150.31258 185

Step:  1900 Cost:  2.7678583 
Prediction:
 [150.75288 185.37042 180.51303 194.10408 144.87907]
Step:  1910 Cost:  2.758881 
Prediction:
 [150.7575  185.36717 180.51437 194.10553 144.8744 ]
Step:  1920 Cost:  2.7499368 
Prediction:
 [150.76213 185.36397 180.51573 194.10703 144.86977]
Step:  1930 Cost:  2.7410417 
Prediction:
 [150.76675 185.36076 180.51707 194.1085  144.86514]
Step:  1940 Cost:  2.7322125 
Prediction:
 [150.77133 185.35754 180.51842 194.10995 144.86052]
Step:  1950 Cost:  2.723378 
Prediction:
 [150.77594 185.35435 180.51976 194.11145 144.85591]
Step:  1960 Cost:  2.7146316 
Prediction:
 [150.7805  185.35118 180.5211  194.11292 144.85132]
Step:  1970 Cost:  2.705928 
Prediction:
 [150.78506 185.34799 180.52245 194.11435 144.84673]
Step:  1980 Cost:  2.697267 
Prediction:
 [150.78961 185.34483 180.52377 194.11581 144.84216]
Step:  1990 Cost:  2.6886432 
Prediction:
 [150.79413 185.34166 180.52509 194.11725 144.83759]
Step:  2000 Cost:  2.6800501 
Prediction:
 [150.79866 

# Hypothesis using Matrix

In [38]:
#data를 matrix로!
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.],
          [96., 98., 100.],[73., 66., 70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

In [39]:
#placeholder for a tensor
#None을 통해서 instance가 늘어나도 shape을 유지하도로 함. (numpy의 -1)
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [40]:
#hypothesis: XW + b
hypothesis = tf.matmul(X,W) + b

In [41]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [42]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [43]:
sess = tf.Session()

In [44]:
sess.run(tf.global_variables_initializer())

In [45]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis, train],
                                  feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print('step: ', step, ', cost: ', cost_val, 
             '\nPrediction: \n', hy_val)

step:  0 , cost:  729.3844 
Prediction: 
 [[132.06567]
 [153.33685]
 [154.0827 ]
 [162.97139]
 [119.99104]]
step:  10 , cost:  6.9691086 
Prediction: 
 [[155.83452]
 [181.91924]
 [182.23807]
 [193.63365]
 [141.7942 ]]
step:  20 , cost:  6.943143 
Prediction: 
 [[155.89903]
 [182.0107 ]
 [182.32088]
 [193.7256 ]
 [141.86598]]
step:  30 , cost:  6.923847 
Prediction: 
 [[155.89183]
 [182.01596]
 [182.31873]
 [193.72502]
 [141.872  ]]
step:  40 , cost:  6.904589 
Prediction: 
 [[155.88441]
 [182.02095]
 [182.31636]
 [193.72424]
 [141.87778]]
step:  50 , cost:  6.8854933 
Prediction: 
 [[155.87704]
 [182.02594]
 [182.31398]
 [193.7234 ]
 [141.88353]]
step:  60 , cost:  6.8664675 
Prediction: 
 [[155.86967]
 [182.0309 ]
 [182.3116 ]
 [193.72258]
 [141.88928]]
step:  70 , cost:  6.8475733 
Prediction: 
 [[155.8623 ]
 [182.03581]
 [182.30923]
 [193.72174]
 [141.89499]]
step:  80 , cost:  6.8287344 
Prediction: 
 [[155.85498]
 [182.04074]
 [182.30687]
 [193.72095]
 [141.90071]]
step:  90 , cos

step:  850 , cost:  5.6247063 
Prediction: 
 [[155.34366]
 [182.3844 ]
 [182.14137]
 [193.66971]
 [142.2939 ]]
step:  860 , cost:  5.6118193 
Prediction: 
 [[155.33766]
 [182.38843]
 [182.1394 ]
 [193.66919]
 [142.29845]]
step:  870 , cost:  5.5990286 
Prediction: 
 [[155.33165]
 [182.39241]
 [182.13744]
 [193.66862]
 [142.30296]]
step:  880 , cost:  5.586236 
Prediction: 
 [[155.32568]
 [182.39644]
 [182.13551]
 [193.66815]
 [142.30748]]
step:  890 , cost:  5.573634 
Prediction: 
 [[155.31975]
 [182.4004 ]
 [182.13358]
 [193.6676 ]
 [142.31198]]
step:  900 , cost:  5.5609775 
Prediction: 
 [[155.3138 ]
 [182.4044 ]
 [182.13164]
 [193.66708]
 [142.31645]]
step:  910 , cost:  5.548393 
Prediction: 
 [[155.30788]
 [182.4084 ]
 [182.12971]
 [193.66658]
 [142.32094]]
step:  920 , cost:  5.535933 
Prediction: 
 [[155.30197]
 [182.41234]
 [182.12778]
 [193.66605]
 [142.3254 ]]
step:  930 , cost:  5.5235014 
Prediction: 
 [[155.29608]
 [182.4163 ]
 [182.12587]
 [193.66553]
 [142.32983]]
step:

step:  1630 , cost:  4.7828207 
Prediction: 
 [[154.91835]
 [182.66905]
 [182.00221]
 [193.63716]
 [142.61005]]
step:  1640 , cost:  4.773859 
Prediction: 
 [[154.9134 ]
 [182.67235]
 [182.0006 ]
 [193.63686]
 [142.61365]]
step:  1650 , cost:  4.764962 
Prediction: 
 [[154.90851]
 [182.67564]
 [181.99901]
 [193.63658]
 [142.61723]]
step:  1660 , cost:  4.756118 
Prediction: 
 [[154.9036 ]
 [182.67891]
 [181.99739]
 [193.63625]
 [142.62077]]
step:  1670 , cost:  4.747323 
Prediction: 
 [[154.89873]
 [182.68216]
 [181.99579]
 [193.63597]
 [142.62434]]
step:  1680 , cost:  4.7384863 
Prediction: 
 [[154.89381]
 [182.68542]
 [181.99417]
 [193.63567]
 [142.62787]]
step:  1690 , cost:  4.7297335 
Prediction: 
 [[154.88896]
 [182.68869]
 [181.99255]
 [193.63538]
 [142.63142]]
step:  1700 , cost:  4.7210755 
Prediction: 
 [[154.88411]
 [182.6919 ]
 [181.99095]
 [193.63507]
 [142.63495]]
step:  1710 , cost:  4.7123995 
Prediction: 
 [[154.8793 ]
 [182.69516]
 [181.98938]
 [193.63483]
 [142.6384

# Loading Data from File

In [46]:
import numpy as np

In [54]:
#data를 받아서 x와 y값으로 분리
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [55]:
#data 확인
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25


Gradient Descent

In [59]:
#placeholder... set the shape as same as the original
x_attr = x_data.shape[1]
y_shape = y_data.shape[1]

X = tf.placeholder(tf.float32, shape = [None, x_attr])
Y = tf.placeholder(tf.float32, shape = [None, y_shape])

W = tf.Variable(tf.random_normal([x_attr,y_shape]), name = 'weight')
b = tf.Variable(tf.random_normal([y_shape]), name = 'bias')

In [60]:
#hypothesis
hypothesis = tf.matmul(X,W) + b

In [61]:
#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [62]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [63]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [70]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X :x_data, Y : y_data})
    if step % 40 == 0:
        print('step: ', step, ' | cost: ', cost_val, '\nPrediction: \n', np.concatenate(hy_val))
        
print('\nY data: ', np.concatenate(y_data))

step:  0  | cost:  6.2420464 
Prediction: 
 [153.13556 184.34476 181.32597 198.80289 139.69046 105.30289 150.88321
 114.6891  174.09305 164.36888 144.0961  142.79437 185.91243 152.69841
 151.78647 188.33258 143.90555 181.73944 176.98611 158.62527 176.40686
 174.29227 167.78952 151.13414 190.319  ]
step:  40  | cost:  6.2412214 
Prediction: 
 [153.13422  184.34657  181.32605  198.80228  139.69325  105.30424
 150.88072  114.684326 174.09465  164.36911  144.09544  142.79497
 185.91331  152.70038  151.78441  188.33344  143.90935  181.73521
 176.98654  158.62517  176.40468  174.29305  167.78737  151.1346
 190.3207  ]
step:  80  | cost:  6.240404 
Prediction: 
 [153.13292 184.34839 181.32617 198.80171 139.69604 105.30559 150.87827
 114.6796  174.09628 164.36935 144.09482 142.79556 185.91422 152.70236
 151.78238 188.33432 143.91313 181.73108 176.987   158.62506 176.40257
 174.29385 167.78526 151.13509 190.32239]
step:  120  | cost:  6.239599 
Prediction: 
 [153.1316   184.35017  181.32625  19

step:  1240  | cost:  6.2225947 
Prediction: 
 [153.09903  184.39403  181.32825  198.78691  139.7659   105.339874
 150.81683  114.5613   174.13759  164.37695  144.07889  142.8111
 185.93576  152.75052  151.73157  188.35622  144.00655  181.62695
 176.99695  158.62128  176.34938  174.31412  167.7321   151.14511
 190.36449 ]
step:  1280  | cost:  6.2221375 
Prediction: 
 [153.09802  184.3954   181.32832  198.7865   139.76799  105.34091
 150.81503  114.557816 174.13887  164.37724  144.07843  142.81158
 185.93639  152.7519   151.73009  188.3569   144.0093   181.62389
 176.99724  158.62117  176.34782  174.31474  167.73055  151.14539
 190.36575 ]
step:  1320  | cost:  6.2216945 
Prediction: 
 [153.09702 184.39676 181.32837 198.78607 139.77005 105.34194 150.81323
 114.55435 174.1401  164.37753 144.07797 142.81207 185.93701 152.7533
 151.72862 188.35756 144.012   181.62085 176.9975  158.62103 176.34628
 174.31537 167.729   151.14563 190.36699]
step:  1360  | cost:  6.2212634 
Prediction: 
 [153

In [72]:
#Ask my score
print('Your score will be ', sess.run(hypothesis, feed_dict = {X:[[100,70,101]]}))
print('Your score will be ', sess.run(hypothesis, feed_dict = {X:[[60,70,110],[90,100,80]]}))

Your score will be  [[186.02472]]
Your score will be  [[183.14635]
 [175.18488]]


## 파일이 너무 큰 경우: Queue Runners
여러개의 파일을 불러 올 경우, Filename Queue에 filename을 쌓고,
이를 각각에 맞게 encoding한 후 다시 Queue를 하면 tensor가 알아서 파일을 읽어준다

In [91]:
# 1. 가지고 있는 파일들의 list를 만들어 주기
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], 
                                                shuffle = False, name = 'filename_queue')

In [92]:
# 2. file을 읽어올 reader를 정의하기
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [93]:
# 3.읽은 value를 parsing 종류에 따라서 읽어주기
record_defaults = [[0.],[0.],[0.],[0.]]  #값이 없을 경우
xy = tf.decode_csv(value, record_defaults = record_defaults)

이 값들을 batch를 통해서 불러오기

In [94]:
#collect batches of csv in 
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size =10)  #한 번에 10개씩 가져와라!

In [95]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [96]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [97]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [98]:
#Start populating the filename queue (general)
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

In [99]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) #이를 feed_dict를 통해 model에 넣어주기
    
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X:x_batch, Y:y_batch})
    if step % 40 == 0:
        print('Batch:  ' , x_batch, y_batch)
        print('step: ', step, ' | cost: ', cost_val, '\nPrediction: \n', np.concatenate(hy_val))
        
print('\nY data: ', np.concatenate(y_data))
    

#general
coord.request_stop()
coord.join(threads)

Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
step:  0  | cost:  46360.773 
Prediction: 
 [-48.634476 -68.012474 -62.04367  -68.35543  -53.554527 -41.723526
 -49.582764 -34.281513 -66.69271  -64.30309 ]
Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
step:  40  | cost:  33.674133 
Prediction: 
 [158.78458  181.49178  183.68701  199.3117   136.74484   98.674164
 150.78877  114.274284 166.59285  151.90004 ]
Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  

Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
step:  840  | cost:  18.410656 
Prediction: 
 [157.2571  182.43394 183.13034 199.35751 137.6156  100.64633 151.01271
 114.62341 168.91422 155.73953]
Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
step:  880  | cost:  17.902018 
Prediction: 
 [157.19383  182.4734   183.10753  199.3592   137.6525   100.727936
 151.02101  114.63596  169.01027  155.89748 ]
Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60

Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
step:  1680  | cost:  10.825864 
Prediction: 
 [156.13377  183.14085  182.72894  199.38362  138.2835   102.09324
 151.14339  114.814964 170.61769  158.52483 ]
Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
step:  1720  | cost:  10.590747 
Prediction: 
 [156.08977 183.16885 182.71341 199.38443 138.3103  102.14981 151.14764
 114.82086 170.68428 158.63293]
Batch:   [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  6

### 참고: Shuffling batch
min_after_dequeue : define how big a buffer we will randomly sample from. 이 값이 클수록 shuffling은 잘 하지만, slower start up and more memory used
                    
capacity: must be larger than min_after_dequeue and the amonunt larger determines the maximum we will prefetch.

In [ ]:
min_after_dequeue = 10000
capacity = min_after_dequeue + 3*batch_size  #recommend: min_after_dequeue + (num_threads + a small safety margin) * batch_size
example_batch, label_batch = tf.train.suffle_batch( [example, label], batch_size = batch_size,
                                                  capacity = capacity, min_after_dequeue = min_after_dequeue)